<?php
    $posts = $block->GetBlog();
?>
 
<table>
  <tr>
        <th class="blog-id">ID</th>
        <th class="blog-name">Title</th>
        <th>Description</th>
  </tr>
    <?php
        foreach ($posts as $data){
            echo '<tr>
                    <td>'.$data->getId().'</td>
                    <td>'.$data->getTitle().'</td>
                    <td>'.$data->getDescription().'</td>
                  </tr>';
        }
    ?>
</table>